# Generated by Django 5.1.7 on 2025-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('public_email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Public Email')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('social_account1', models.CharField(blank=True, max_length=200)),
                ('social_account2', models.CharField(blank=True, max_length=200)),
                ('social_account3', models.CharField(blank=True, max_length=200)),
                ('social_account4', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('normal', 'Normal User'), ('contributor', 'Contributor')], default='normal', max_length=20)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
