# Generated by Django 5.1.6 on 2025-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_bio_user_is_superuser_user_public_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('contributor', 'Contributor')], default='normal', max_length=20),
        ),
    ]
