# Generated by Django 5.1.7 on 2025-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
