# Generated by Django 5.1.4 on 2025-01-05 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributorid', models.AutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='media/licenses/')),
                ('government_card', models.ImageField(blank=True, null=True, upload_to='media/government_cards/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
