# Generated by Django 5.1.7 on 2025-04-18 14:22

from django.db import migrations, models 


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_user'),
    ]

    operations = [
        migrations.AddField(
        model_name='payment',
        name='status',
        field=models.BooleanField(default=False),
    ),
    ]
