# Generated by Django 5.1.7 on 2025-04-18 14:46
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20250418_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=4, blank=True, editable=False),
        ),
    ]
